### ISSUE TITLE
'labels' key may not be present in pod['properties]

### ISSUE THREAD

**Issue by vasbala** [google/cluster-insight#21]
The 'labels' key is not guaranteed to exist for all Pods. Thus, the following statement in kubernetes.py:182 can fail with a KeyError:

  if not isinstance(pod['properties']['labels'], types.DictType):
    return False

This should be re-written as:

  if ('labels' not in pod['properties']) or (not isinstance(pod['properties']['labels'], types.DictType)):
    return False

**Comment by EranGabber** [comment]
Fixed by pull request #23.
