### ISSUE TITLE
compute similar subgraphs

### ISSUE THREAD

**Issue by EranGabber** [google/cluster-insight#27]
The definition of similarity is hard. We can start by requiring identical structure and relations. Relations that extend outside the subgraph should be handled with care. "monitors" and "loadBalances" should have the same source resource. "runs" may have a different source node. "contains" must have equivalent source and target resources.

**Comment by vasbala** [comment]
Eran

We should discuss whether similarity detection should be in open source or
a proprietary backend we develop as a product. I suggest deleting this
issue in github until we make that decision and get Jeromy's approval.

Vas

On Mar 30, 2015, at 7:23 PM, Eran Gabber <notifications@github.com> wrote:

The definition of similarity is hard. We can start by requiring identical
structure and relations. Relations that extend outside the subgraph should
be handled with care. "monitors" and "loadBalances" should have the same
source resource. "runs" may have a different source node. "contains" must
have equivalent source and target resources.

—
Reply to this email directly or view it on GitHub
<https://github.com/google/cluster-insight/issues/27>.
