### ISSUE TITLE
some services/replicationControllers and related pods are not connected in the context graph.

### ISSUE THREAD

**Issue by supriyagarg** [google/cluster-insight#41]
In the cassandra cluster setup, two of the services are not connected to their respective pods: cassandra and monitoring-heapster. In the case of cassandra, the replication controller and pods are not connected either. The heapster rc is fine - it has the expected link to its pod.

The selector for the service/rc, and the label for the pods do have a match in both cases. Here is the status from the dev cluster (the-pentameter-90318):

__For cassandra:__
* Service: `cassandra`
* Service Selector: `name=cassandra`
* Pods (4): `cassandra-a6pnt, cassandra-a8pbs, cassandra-hnj3i, cassandra-svacm`
* Pod labels: `name=cassandra`
* Replication Controller: `cassandra`
* Replication Controller selector: `name=cassandra`

__For heapster:__
* Service: `monitoring-heapster`
* Service Selector: `name=heapster`
* Pod: `monitoring-heapster-controller-1gapo`
* Pod labels: `kubernetes.io/cluster-service=true,name=heapster`

**Comment by EranGabber** [comment]
Closed by pull request https://github.com/google/cluster-insight/pull/43.
