### ISSUE TITLE
cannot locate parent pod in GKE cluster

### ISSUE THREAD

**Issue by supriyagarg** [google/cluster-insight#58]
In the GKE cluster, the API call to /cluster/resources/containers returns an error message:

{
  "error_message": "u'could not locate parent pod cassandra.f20d7205_cassandra for container k8s_cassandra.f20d7205_cassandra_default_2a3763eb-d7be-11e4-8153-42010af03474_94d86795'", 
  "success": false, 
  "timestamp": "2015-05-04T15:17:11.642006"
}

**Comment by EranGabber** [comment]
Which cluster was it? I would like to verify that this problem was fixed by my recent changes.

**Comment by supriyagarg** [comment]
It was the GKE cassandra cluster - I re-installed the cluster to get heapster to work, and don't see this error any more. The graph also looks good - i.e. all containers have a pod as parent.

I think you can close this issue.

**Comment by EranGabber** [comment]
This problem was fixed by #67.
