### ISSUE TITLE
error thrown for API calls in new version of kubernetes

### ISSUE THREAD

**Issue by supriyagarg** [google/cluster-insight#59]
In version 0.15 of kubernetes, apiVersion v1beta3 is the default. The current dev cluster runs this version.

For this version of kubernetes, cluster insight throws assertion errors for some API calls:
*  /cluster/resources/nodes
* /cluster/resources/containers
* /cluster/resources/processes
* /cluster/resources/images

The error originates in the same place:

    Traceback (most recent call last):
    ...
      File "/usr/src/app/kubernetes.py", line 116, in get_nodes
        label=utilities.node_id_to_host_name(node['id']))
      File "/usr/src/app/utilities.py", line 358, in node_id_to_host_name
        assert m
    AssertionError

The NODE_ID_PATTERN in utilites.py is not valid anymore. The node_id no longer contains the project name. It's format has changed as follows:

    "kubernetes-minion-ycym.c.gce-monitoring.internal" -> "kubernetes-minion-ycym"

**Comment by EranGabber** [comment]
Closed by https://github.com/google/cluster-insight/pull/66.
