### ISSUE TITLE
when a container has no parent pod, the /cluster/resources/containers throws an error

### ISSUE THREAD

**Issue by supriyagarg** [google/cluster-insight#70]
It is possible to have a container with no parent pod. So when the parent_pod_id is None, instead of throwing an error,  we should record the container.

E.g. of such a scenario:

When the cluster-insight container was started on a minion directly (rather than using the replication controller), this error was thrown.

**Comment by EranGabber** [comment]
The error message is:
"error_message": "u'missing or invalid parent pod ID in container cluster-insight'",
