### ISSUE TITLE
images with identical names are not merged

### ISSUE THREAD

**Issue by EranGabber** [google/cluster-insight#73]
The context graph of the test cluster shows multiple separate instances of the image "Image:kubernetes/cluster-insight", which are not collapsed together.

Interestingly, the label of the container is the same, but the underlying image ID is different.
Maybe this is the result of compiling the image from sources in each node.

**Comment by supriyagarg** [comment]
That is correct - the image ID is different due to local compilation. When the cluster is set up to pull from the docker hub, there is only 1 image for kubernetes/cluster-insight.

**Comment by EranGabber** [comment]
Once I started the Cluster-Insight collector from the binary fetched from Docker Hub, all images collapsed as expected. The current code works as expected.
