### ISSUE TITLE
latest container image fails to run in some nodes

### ISSUE THREAD

**Issue by EranGabber** [google/cluster-insight#94]
After running the installation script in production mode, some of the minion containers fail to run (fail to start or die and not restarted by the replication controller). I am using the latest container image that Supriya built today.

Some interesting observations:
on node kubernetes-minion-9ura:
$ sudo docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
&lt;none&gt;                                           &lt;none&gt;              1635f364fdf7        8 hours ago         681.2 MB
kubernetes/cluster-insight                       latest              4351b5df5f3b        9 hours ago         681.3 MB

The most recent image from Docker Hub is image ID 1635f364fdf7. Although it was built most recently, an earlier version that I built locally still keeps the "latest" tag (image ID 4351b5df5f3b).

The output of the "sudo docker images" is correct in a different node, kubernetes-minion-5emu:
$ sudo docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
kubernetes/cluster-insight                       latest              1635f364fdf7        8 hours ago         681.2 MB
&lt;none&gt;                                            &lt;none&gt;              068269233f0d        9 hours ago         681.3 MB

**Comment by supriyagarg** [comment]
Always pulling the image is what is causing the issue. On the GKE cluster, I initially saw this:
* Only the master pod was pending. It had not even pulled the cluster-insight image

When I changed imagePullPolicy to IfNotPresent for the master-controller, 
* Only the master pod was running. All the minion pods were pending - again without even pulling the image.

Since the master & minion use the same image,  this setup is causing problems.

**Comment by supriyagarg** [comment]
I think we should add a version number to the images we upload to docker hub. That way the yaml files can be very clean - just have the image name be: kubernetes/cluster-insight:VERSION_NUMBER. No need for `imagePullPolicy` to be `Always`

**Comment by EranGabber** [comment]
I was able to replicate this problem reliably on "nth-segment" cluster. I am using the latest version of the installation script.

I changed the production master and minion template files to be identical to the corresponding debug template files. Executing ./cluster-insight/install/cluster-insight-setup.sh sets the cluster-insight successfully. I then changed the "imagePullPolicy" attribute in the master and minion template files from "IfNotPresent" to "Always". Executing ./cluster-insight/install/cluster-insight-setup.sh now fails reliably with the message:
FAILED to get service health response.

Accessing the service's /healthz endpoint produces the following error:
$ curl http://localhost:8001/api/v1/proxy/namespaces/default/services/cluster-insight:cluster-insight/healthz
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for \"cluster-insight\"",
  "code": 500
}

Listing the running containers on the minion nodes show:
kubernetes-minion-z4dv:
$ sudo docker ps
48f490d0139a        gcr.io/google_containers/pause:0.8.0                 "/pause"               About an hour ago  
 Up About an hour    0.0.0.0:4243->4243/tcp   k8s_POD.baeedb8_cluster-insight-minion-controller-v1-jbm6k_default_c90e2031-1ff5-11e5-a2f4-42010af0216b_0bbe74d3

(the collector minion is not running, but its proxy is running and listening on port 4243)
same situation on kubernetes-minion-9ura and on ubernetes-minion-y02e.

On kubernetes-minion-5emu there are two proxies running and no master or minion collectors:
0fd4a18233f3        gcr.io/google_containers/pause:0.8.0                 "/pause"               About an hour ago  
 Up About an hour    0.0.0.0:5555->5555/tcp   k8s_POD.6e0eef86_cluster-insight-master-controller-v1-w69pb_default_c9a9d107-1ff5-11e5-a2f4-42010af0216b_b208f8ed                   
16b8afded4e2        gcr.io/google_containers/pause:0.8.0                 "/pause"               About an hour ago  
 Up About an hour    0.0.0.0:4243->4243/tcp   k8s_POD.baeedb8_cluster-insight-minion-controller-v1-nbrqa_default_c869688c-1ff5-11e5-a2f4-42010af0216b_a259143c

I believe that this problem is caused by something connected to the binary you just pushed. It may also be related to the content of the container images repository in the minion nodes, as I explained above.

**Comment by EranGabber** [comment]
A more succinct problem description on the "nth-segment" cluster:
when "imagePullPolicy: Always", the containers fail to start.
when "imagePullPolicy: IfNotPresent", the containers start and behave as expected.

**Comment by EranGabber** [comment]
Having an explicit version number is somewhat painful, because we have to assign unique version numbers when we build the binaries (or assign a tag to them), and then update the template files in 4 places (master/minion)x(production/debug) templates.

**Comment by EranGabber** [comment]
The solution is to pull an explicit version of the container image from the production template files.
This image is pull with "imagePullPolicy: IfNotPresent" to reduce the load on Docker Hub.

When we create a new binary, we should tag it with the current date (like: 2015-07-01) and change the version tag in the two production template files (install/cluster-insight-{master,minion}-controller.yaml).
There is no need to change the debug template files.

**Comment by EranGabber** [comment]
Closed by PR #96.
